lib: [
  "_build/install/default/lib/aoc/2024/day_01.ml" {"2024/day_01.ml"}
  "_build/install/default/lib/aoc/2024/day_02.ml" {"2024/day_02.ml"}
  "_build/install/default/lib/aoc/2024/day_03.ml" {"2024/day_03.ml"}
  "_build/install/default/lib/aoc/2024/day_04.ml" {"2024/day_04.ml"}
  "_build/install/default/lib/aoc/2024/y2024.a" {"2024/y2024.a"}
  "_build/install/default/lib/aoc/2024/y2024.cma" {"2024/y2024.cma"}
  "_build/install/default/lib/aoc/2024/y2024.cmi" {"2024/y2024.cmi"}
  "_build/install/default/lib/aoc/2024/y2024.cmt" {"2024/y2024.cmt"}
  "_build/install/default/lib/aoc/2024/y2024.cmx" {"2024/y2024.cmx"}
  "_build/install/default/lib/aoc/2024/y2024.cmxa" {"2024/y2024.cmxa"}
  "_build/install/default/lib/aoc/2024/y2024.ml" {"2024/y2024.ml"}
  "_build/install/default/lib/aoc/2024/y2024__Day_01.cmi" {"2024/y2024__Day_01.cmi"}
  "_build/install/default/lib/aoc/2024/y2024__Day_01.cmt" {"2024/y2024__Day_01.cmt"}
  "_build/install/default/lib/aoc/2024/y2024__Day_01.cmx" {"2024/y2024__Day_01.cmx"}
  "_build/install/default/lib/aoc/2024/y2024__Day_02.cmi" {"2024/y2024__Day_02.cmi"}
  "_build/install/default/lib/aoc/2024/y2024__Day_02.cmt" {"2024/y2024__Day_02.cmt"}
  "_build/install/default/lib/aoc/2024/y2024__Day_02.cmx" {"2024/y2024__Day_02.cmx"}
  "_build/install/default/lib/aoc/2024/y2024__Day_03.cmi" {"2024/y2024__Day_03.cmi"}
  "_build/install/default/lib/aoc/2024/y2024__Day_03.cmt" {"2024/y2024__Day_03.cmt"}
  "_build/install/default/lib/aoc/2024/y2024__Day_03.cmx" {"2024/y2024__Day_03.cmx"}
  "_build/install/default/lib/aoc/2024/y2024__Day_04.cmi" {"2024/y2024__Day_04.cmi"}
  "_build/install/default/lib/aoc/2024/y2024__Day_04.cmt" {"2024/y2024__Day_04.cmt"}
  "_build/install/default/lib/aoc/2024/y2024__Day_04.cmx" {"2024/y2024__Day_04.cmx"}
  "_build/install/default/lib/aoc/META"
  "_build/install/default/lib/aoc/dune-package"
  "_build/install/default/lib/aoc/opam"
]
libexec: [
  "_build/install/default/lib/aoc/2024/y2024.cmxs" {"2024/y2024.cmxs"}
]
bin: [
  "_build/install/default/bin/main"
]
